name: extensionresoft
description: Boost your Flutter development with reusable widgets, utilities, and extensions
  for advanced image handling, secure PIN entry, internet connectivity checks, storage management, and more.
version: 1.0.0
homepage: https://github.com/kenresoft/extensionresoft
repository: https://github.com/kenresoft/extensionresoft
issue_tracker: https://github.com/kenresoft/extensionresoft/issues
#documentation: https://github.com/kenresoft/extensionresoft
topics: [ flutter, widgets, extensions, image, network, connectivity, storage, PIN entry, development, efficiency, productivity ]

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=3.16.5"

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.3.5
  connectivity_plus: ^6.1.1
  equatable: ^2.0.7
  rxdart: ^0.28.0
  cached_network_image: ^3.4.1
  logger: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
