name: extensionresoft
description: A collection of Dart/Flutter Extension functions and Helper functions for faster development. 
  This was developed to aide developers write minimized but powerful codes. 
  It absolutely makes for codes re-usability and easy coding reading.
version: 0.0.1
homepage:

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=3.16.5"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true


